export type LinkItem = {
    id: number;
    name: string;
    link: string;
    linkP: string;
    linkG: string;
    linkMV1: string;
    linkMV2: string;
    linkMV3: string;
    linkP: string;
    linkG: string;
    linkMV1: string;
    linkMV2: string;
    linkMV3: string;
    category: string;
    postDate: string;
    createdAt: string;
    updatedAt: string;
    slug: string;
    thumbnail?: string;
  };